# Generated by Django 4.1.7 on 2023-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, default='images/auto.jpg', upload_to='images/'),
        ),
    ]
