# Generated by Django 4.1.7 on 2023-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatedblog', '0002_topic_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, default='images/auto.png', upload_to='images/'),
        ),
    ]
